"""Description of changes

Revision ID: 8bde012b63dd
Revises: 9a1d572276cd
Create Date: 2024-05-08 19:57:20.284841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bde012b63dd'
down_revision = '9a1d572276cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
